language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.2
    - build-tools-27.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
before_install:
- chmod +x gradlew
- chmod +rx app
skip_cleanup: true
script:
- ./gradlew clean build ktlint
- export CI=true
- export CI_NAME=travis-ci
- ./gradlew jacocoTestReport coveralls
after_success:
- curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST \
 -d "{\"body\": \"Hello world2\"}" \
"https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"